flowchart LR
  a1((_:a1)) -->|rdf:first| c01[ex:c01]
  a1 -->|rdf:rest| l2((_:l2))
  b1((_:b1)) -->|rdf:first| c02[ex:c02]
  b1 -->|rdf:rest| l2
  l2 -->|rdf:first| c03[ex:c03]
  l2 -->|rdf:rest| nil[rdf:nil]
